version: '2.1'
services:
  postgres:
    image: postgres
    env_file: .env.local
    environment:
      POSTGRES_DB: analytics
    ports:
    - '54321:5432'
    logging:
      driver: "none"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d analytics -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build: .
    image: commentbox/commentbox.io-analytics
    command: nodemon start.js
    env_file: .env.local
    ports:
    - '3000:3000'
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    links:
    - postgres